### ISSUE TITLE
solox 1.0.4在windows上启动报错

### ISSUE THREAD

**Issue by yhforthefreedom** [rafa0128/SoloX#5]
C:\>python -m solox
Traceback (most recent call last):
  File "D:\environment\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\environment\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\environment\python\lib\site-packages\solox\__main__.py", line 4, in <module>
    from .view.apis import api
  File "D:\environment\python\lib\site-packages\solox\view\apis.py", line 5, in <module>
    from public.apm import *
ModuleNotFoundError: No module named 'public'

**Comment by rafa0128** [comment]
你好，目前只支持python3，最新版本是1.0.28，请更新pip3 install -U solox

**Comment by rafa0128** [comment]
> C:>python -m solox Traceback (most recent call last): File "D:\environment\python\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\environment\python\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\environment\python\lib\site-packages\solox__main__.py", line 4, in from .view.apis import api File "D:\environment\python\lib\site-packages\solox\view\apis.py", line 5, in from public.apm import * ModuleNotFoundError: No module named 'public'

**Comment by rafa0128** [comment]
你好，目前只支持python3（执行请用python3 -m  solox），最新版本是1.0.28，请更新pip3 install -U solox
